version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /path/on/host:/data
    command: redis-server --appendonly yes

  Mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata:

# version: '3'
# services:
#   redis:
#     image: redis:latest
#     ports:
#       - "6379:6379"
